<a href="https://colab.research.google.com/github/eluizaTsuda/fcc-data-analysis-with-python/blob/main/DataAnalysisWithPython-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b[0], b[2], [b-1]

(0.0, 1.0, [array([-1. , -0.5,  0. ,  0.5,  1. ])])

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3, 4], dtype=np.float)

<ipython-input-17-6aadc0eb779c>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [18]:
c = np.array(['a', 'b', 'c'])

In [19]:
c.dtype

dtype('<U1')

In [20]:
d = np.array([{'a': 1}, sys])

In [21]:
d.dtype

dtype('O')

In [22]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [23]:
A.shape

(2, 3)

In [24]:
A.ndim

2

In [25]:
A.size

6

In [26]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [27]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [28]:
B.shape


(2, 2, 3)

In [29]:
B.ndim

3

In [30]:
B.size

12

In [7]:
C = np.array([
    [
      [12,11,10],
      [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

<ipython-input-7-8af2fd54212f>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [8]:
C.dtype

dtype('O')

In [9]:
C.shape

(2,)

In [10]:
C.size

2

In [12]:
type(C[0])

list

**Indexing and Slicing of Matrices**

In [13]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [15]:
A[1]

array([4, 5, 6])

In [14]:
A[1][0]

4

In [16]:
A [1, 0]

4

In [17]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [19]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [20]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
A[1] = np.array([10, 10, 10])

In [22]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [23]:
A[2] = 99

In [24]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

**Summary Statistics**

In [25]:
a = np.array([1, 2, 3, 4])

In [26]:
a.sum()

10

In [27]:
a.mean()

2.5

In [28]:
a.std()

1.118033988749895

In [29]:
a.var()

1.25

In [30]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [31]:
A.sum()

45

In [32]:
A.mean()


5.0

In [33]:
A.std()

2.581988897471611

In [34]:
A.sum(axis=0)

array([12, 15, 18])

In [35]:
A.sum(axis=1)

array([ 6, 15, 24])

In [36]:
A.mean(axis=0)

array([4., 5., 6.])

In [37]:
A.mean(axis=1)

array([2., 5., 8.])

**Broadcasting and Vectorized Operations**

In [38]:
a = np.arange(4)

In [39]:
a

array([0, 1, 2, 3])

In [40]:
a + 10

array([10, 11, 12, 13])

In [41]:
a * 10

array([ 0, 10, 20, 30])

In [42]:
a

array([0, 1, 2, 3])

In [43]:
a += 100

In [44]:
a

array([100, 101, 102, 103])

In [46]:
l = [0, 1, 2, 3]

In [48]:
(i * 10 for i in l)

<generator object <genexpr> at 0x7f308af1ad60>

In [50]:
a = np.arange(4)

In [51]:
a

array([0, 1, 2, 3])

In [52]:
b = np.array([10, 10, 10, 10])

In [53]:
a + b

array([10, 11, 12, 13])

In [54]:
a * b

array([ 0, 10, 20, 30])

**Boolean arrays**

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
a[[0, -1]]

array([0, 3])

In [5]:
a[[True, False, False, True]]

array([0, 3])

In [6]:
a * 10

array([ 0, 10, 20, 30])

In [7]:
a >= 2

array([False, False,  True,  True])

In [9]:
a[a >= 2]

array([2, 3])

In [8]:
a.mean()

1.5

In [10]:
a[a > a.mean()]

array([2, 3])

In [12]:
a[~(a > a.mean())]

array([0, 1])

In [13]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [14]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [15]:
A = np.random.randint(100, size = (3, 3))

In [16]:
A

array([[75, 61, 14],
       [37,  0, 43],
       [24,  7, 93]])

In [17]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([75, 14,  0, 24, 93])

In [18]:
A > 30

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [19]:
A[A > 30]

array([75, 61, 37, 43, 93])